# Generated by Django 6.0.5 on 2026-05-22 07:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0005_alter_ingredient_amount_alter_recipe_meal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в %')),
                ('valid_from', models.DateTimeField(db_index=True, verbose_name='Действителен с')),
                ('valid_to', models.DateTimeField(db_index=True, verbose_name='Действителен до')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], default=1, verbose_name='Срок подписки (мес)')),
                ('persons_count', models.IntegerField(choices=[(1, '1 персона'), (2, '2 персоны'), (3, '3 персоны'), (4, '4 персоны'), (5, '5 персон'), (6, '6 персон')], default=1, verbose_name='Количество персон')),
                ('has_breakfast', models.BooleanField(default=True, verbose_name='Завтраки')),
                ('has_lunch', models.BooleanField(default=True, verbose_name='Обеды')),
                ('has_dinner', models.BooleanField(default=True, verbose_name='Ужины')),
                ('has_dessert', models.BooleanField(default=True, verbose_name='Десерты')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Оплачен')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('excluded_allergens', models.ManyToManyField(blank=True, related_name='orders_excluded', to='menu.allergen', verbose_name='Исключенные аллергены')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='menu.menu', verbose_name='Тип меню')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='DailyRation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата рациона')),
                ('total_calories', models.PositiveIntegerField(default=0, verbose_name='Всего калорий')),
                ('breakfast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='menu.recipe')),
                ('dessert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='menu.recipe')),
                ('dinner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='menu.recipe')),
                ('lunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='menu.recipe')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rations', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Дневной рацион',
                'verbose_name_plural': 'Дневные рационы',
                'unique_together': {('order', 'date')},
            },
        ),
    ]
