# Generated by Django 6.0.5 on 2026-05-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='menu',
            new_name='menu_type',
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('classic', 'Классическое'), ('low_carb', 'Низкоуглеводное'), ('vegetarian', 'Вегетарианское'), ('keto', 'Кето')], max_length=20, unique=True, verbose_name='Тип меню'),
        ),
    ]
