# Generated by Django 6.0.5 on 2026-05-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_allergen_menu_image_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(max_length=50, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('dessert', 'Десерт')], default='breakfast', max_length=20, verbose_name='Тип приёма пищи'),
        ),
    ]
